apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque # Default type (stores generic key-value pairs)
data:
  DB_USERNAME: dXNlcm5hbWU=   # base64 encoded value of 'username'
  DB_PASSWORD: cGFzc3dvcmQ=   # base64 encoded value of 'password'
  DB_NAME: ZGF0YWJhc2U=       # base64 encoded value of 'database'
  DB_PORT: MzMwNg==           # base64 encoded value of '3306'
