apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-example
spec:
  rules:
    - host: "example.com"
      http:
        paths:
          - pathType: Prefix
            path: "/v1"
            backend:
              service:
                name: go-k8s-app-service
                port:
                  number: 80
