apiVersion: v1
kind: Service
metadata:
  name: go-k8s-app-service
spec:
  type: NodePort
  # Want to access publicly, we need to use service type LoadBalancer.Locally not work because LoadBalancer type-only support by Cloud Provider
  # type: LoadBalancer
  selector:
    app: go-k8s-sample-app
  ports:
    - protocol: TCP
      port: 80
      # By default, and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 8080
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # auto-assigned if not specified a port from a range (default: 30000-32767)
      nodePort: 30007